import { defineConfig } from "tsup";

// Builds standard ESM + .d.ts so the library is consumable BOTH ways:
//   - importmap-rails: pin the emitted dist/index.js directly
//   - jsbundling-rails (esbuild/bun): `bun link` + `import "stimeo-ui"`
// @hotwired/stimulus is kept external; the consuming Rails app provides it.
export default defineConfig({
  entry: [
    "src/index.ts",
    "src/controllers/accordion_controller.ts",
    "src/controllers/announcer_controller.ts",
    "src/controllers/aspect_ratio_controller.ts",
    "src/controllers/auto_submit_controller.ts",
    "src/controllers/avatar_controller.ts",
    "src/controllers/breadcrumb_controller.ts",
    "src/controllers/bulk_select_controller.ts",
    "src/controllers/calendar_controller.ts",
    "src/controllers/character_counter_controller.ts",
    "src/controllers/checkbox_controller.ts",
    "src/controllers/combobox_controller.ts",
    "src/controllers/command_palette_controller.ts",
    "src/controllers/conditional_fields_controller.ts",
    "src/controllers/confirm_controller.ts",
    "src/controllers/context_menu_controller.ts",
    "src/controllers/countdown_controller.ts",
    "src/controllers/dialog_controller.ts",
    "src/controllers/direct_upload_controller.ts",
    "src/controllers/dirty_form_controller.ts",
    "src/controllers/dropdown_controller.ts",
    "src/controllers/empty_state_controller.ts",
    "src/controllers/flash_controller.ts",
    "src/controllers/focus_controller.ts",
    "src/controllers/form_field_controller.ts",
    "src/controllers/form_validation_controller.ts",
    "src/controllers/frame_loading_controller.ts",
    "src/controllers/highlight_controller.ts",
    "src/controllers/hover_card_controller.ts",
    "src/controllers/idle_controller.ts",
    "src/controllers/input_mask_controller.ts",
    "src/controllers/lazy_frame_controller.ts",
    "src/controllers/listbox_controller.ts",
    "src/controllers/local_time_controller.ts",
    "src/controllers/menu_controller.ts",
    "src/controllers/meter_controller.ts",
    "src/controllers/nested_form_controller.ts",
    "src/controllers/network_status_controller.ts",
    "src/controllers/number_input_controller.ts",
    "src/controllers/otp_controller.ts",
    "src/controllers/overflow_indicator_controller.ts",
    "src/controllers/overflow_menu_controller.ts",
    "src/controllers/pagination_controller.ts",
    "src/controllers/password_strength_controller.ts",
    "src/controllers/persist_controller.ts",
    "src/controllers/popover_controller.ts",
    "src/controllers/portal_controller.ts",
    "src/controllers/preview_guard_controller.ts",
    "src/controllers/progress_controller.ts",
    "src/controllers/radio_group_controller.ts",
    "src/controllers/rating_controller.ts",
    "src/controllers/relative_time_controller.ts",
    "src/controllers/reset_before_cache_controller.ts",
    "src/controllers/resizable_controller.ts",
    "src/controllers/roving_controller.ts",
    "src/controllers/scroll_area_controller.ts",
    "src/controllers/scroll_visibility_controller.ts",
    "src/controllers/scrollspy_controller.ts",
    "src/controllers/skeleton_controller.ts",
    "src/controllers/slider_controller.ts",
    "src/controllers/spinner_controller.ts",
    "src/controllers/step_indicator_controller.ts",
    "src/controllers/stepper_controller.ts",
    "src/controllers/stick_to_bottom_controller.ts",
    "src/controllers/sticky_observer_controller.ts",
    "src/controllers/submit_once_controller.ts",
    "src/controllers/switch_controller.ts",
    "src/controllers/tabs_controller.ts",
    "src/controllers/textarea_autosize_controller.ts",
    "src/controllers/theme_controller.ts",
    "src/controllers/toast_controller.ts",
    "src/controllers/toggle_group_controller.ts",
    "src/controllers/toolbar_controller.ts",
    "src/controllers/tooltip_controller.ts",
    "src/controllers/transition_controller.ts",
    "src/positioning/index.ts",
    "src/inspector/cli.ts",
    "src/inspector/cli_bin.ts",
  ],
  format: ["esm"],
  target: "es2022",
  dts: true,
  clean: true,
  sourcemap: true,
  splitting: false,
  treeshake: true,
  // @floating-ui/dom stays external: it is an OPTIONAL peer pulled in only by the
  // opt-in `stimeo-ui/positioning` subpath, never by the core. The audit allows
  // this bare import solely under `positioning/` so the core stays zero-dep.
  external: ["@hotwired/stimulus", "@floating-ui/dom"],
  outDir: "dist",
});
