// Registers every stimeo--* controller with the app's Stimulus application.
// Generated by `rails g stimeo:install`. Safe to edit.
//
// To cherry-pick instead of registering all controllers, import them
// individually from "stimeo-ui/controllers/<name>" and register under your own
// identifiers. Note: with a JS bundler this works as-is; with importmap-rails
// each "stimeo-ui/controllers/<name>" needs its own pin (this generator only
// pins the "stimeo-ui" entrypoint), so add those pins to config/importmap.rb.
import { application } from "controllers/application";
import { registerStimeo } from "stimeo-ui";

registerStimeo(application);
